### ISSUE TITLE
请问这种情况怎么解决？

### ISSUE THREAD

**Issue by kaierrao** [lscho/ThinkJS-Vue.js-blog#14]
- D:\code\blog\ThinkJS-Vue.js-blog-master\node_modules\think-session-jwt\index.js:28
  async initSessionData() {
       
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\code\blog\ThinkJS-Vue.js-blog-master\src\config\adapter.js:2:20)

**Comment by lscho** [comment]
低于7.6.0的话升级一下试试
