### ISSUE TITLE
请问现在项目还在维护吗 启动后台服务部分运行不起来了

### ISSUE THREAD

**Issue by analwang** [lscho/ThinkJS-Vue.js-blog#66]
目前运行如下：
npm start

> admin@1.0.0 start F:\Documents\blog\ThinkJS-Vue.js-blog\admin
> npm run dev

> admin@1.0.0 dev F:\Documents\blog\ThinkJS-Vue.js-blog\admin
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

TypeError: compiler.getInfrastructureLogger is not a function
    at HtmlWebpackPlugin.apply (F:\Documents\blog\ThinkJS-Vue.js-blog\admin\node_modules\html-webpack-plugin\index.js:72:28)
    at Compiler.apply (F:\Documents\blog\ThinkJS-Vue.js-blog\admin\node_modules\webpack\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (F:\Documents\blog\ThinkJS-Vue.js-blog\admin\node_modules\webpack\lib\webpack.js:33:19)
    at startDevServer (F:\Documents\blog\ThinkJS-Vue.js-blog\admin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:367:16)
    at processOptions (F:\Documents\blog\ThinkJS-Vue.js-blog\admin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:350:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

请问有什么修改建议吗 我在网上找到的对我帮助不大

**Comment by analwang** [comment]
刚看到您9月还有提交 不好意思
